branch-defaults:
  default:
    environment: thuong-api-3
    group_suffix: null
global:
  application_name: thuong-api-3
  branch: null
  default_ec2_keyname: thuongtn
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
