branch-defaults:
  default:
    environment: Thuongtn3udagramnanoapi-env
    group_suffix: null
global:
  application_name: thuongtn3-udagram-nano-api
  branch: master
  default_ec2_keyname: thuongtn-eb-key-pair
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
